[package]
name = "enet-sys"
edition = "2021"
version = "1.0.5"
authors = ["Roland Ruckerbauer <roland.rucky@gmail.com>"]
description = "Low level bindings to the enet C library"
license = "MIT"
repository = "https://github.com/ruabmbua/enet-sys"
links = "enet"
build = "build.rs"

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1.44"
